name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  non:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  local:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --features local
  redis:
    runs-on: ubuntu-latest
    services:
      redis:
        image: bitnami/redis
        env:
          ALLOW_EMPTY_PASSWORD: yes
          REDIS_DISABLE_COMMANDS: FLUSHDB,FLUSHALL
        ports:
          - '6379:6379'
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --features redis
  nats:
    runs-on: ubuntu-latest
    services:
      nats: 
        image: bitnami/nats
        ports:
          - 4222:4222
          - 6222:6222
          - 8222:8222
        env:
          NATS_USERNAME: nats
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --features nats
